apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/pg
  # nfs:
  #   server: 192.168.1.10
  #   path: "/data/nfs/pg"
  # cephfs:
  #   readOnly: false
  #   monitors:
  #     - 192.168.1.10:6789
  #   user: admin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
  volumeName: postgres-pv
  volumeMode: Filesystem
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: NodePort
  ports:
    - name: "tcp"
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          imagePullPolicy: Always
          env:
            # - name: PGDATA
            #   value: /var/lib/postgresql-static/data
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            # - mountPath: /var/lib/postgresql-static/data
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-claim
